/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <I2C.h>
#include <VIM_878.h>
#include <Usart_Setup.h>


int data[3] = {3,3,3};

int main(void)
{
	/* Init FPU*/
	SCB->CPACR |= ((3UL << 20)|(3UL << 22));
	i2c1_init();
	lcd_init();
	burst_write(6,3, (int*)data);

	while(1){

	}
}
